apiVersion: v1
kind: Service
metadata:
  name: nats-nlb
  namespace: default
  labels:
    app: nats
  annotations:
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: nats
    port: 4222
    protocol: TCP
    targetPort: 4222
  - name: nats-gateway
    port: 7522
    protocol: TCP
    targetPort: 7522
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app.kubernetes.io/name: nats
